# Generated by Django 2.0 on 2018-09-09 13:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('source_position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('source_name', models.CharField(blank=True, max_length=255, null=True)),
                ('destination_position', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('destination_name', models.CharField(blank=True, max_length=255, null=True)),
                ('booked_for_date', models.DateField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.Company')),
            ],
        ),
    ]
